// Macros for PIN and PORTs
#define PIN_BUTTON_USER 2
#define DEBOUNCE_TIME_MILLIS 100
// Radio
#define PIN_RF_RX 3

#define PORT_PORT_RF_RX PIND
#define PORT_PIN_RF_RX 3

// Buzzer
#define PIN_BUZZER 5

// Relay
#define PIN_RELAY 7

#define PIN_I2C_SCL A5
#define PIN_I2C_SDA A4

// Macros for buzzer volume selections
#define BUZZER_LOW_VOLUME 17000
#define BUZZER_MEDIUM_VOLUME 300
#define BUZZER_HIGH_VOLUME 5000
#define BUZZER_TIME_MILLIS 100

// Macros for LCD handing
#define I2C_SLAVE_ADDRESS 8

// Flag mask macro for I2C message
#define FLAG_BIT_BUZZER 0x80
#define COMMAND_BUZZER_LOW_VOLUME (FLAG_BIT_BUZZER | 0x0)
#define COMMAND_BUZZER_MEDIUM_VOLUME (FLAG_BIT_BUZZER | 0x20)
#define COMMAND_BUZZER_HIGH_VOLUME (FLAG_BIT_BUZZER | 0x40)
#define COMMAND_BUZZER_CHANGE (FLAG_BIT_BUZZER | 0x60)
#define COMMAND_LIGHT_ON 0x20
#define COMMAND_LIGHT_OFF 0x40
#define COMMAND_LIGHT_CHANGE 0x60

#define FLAG_MASK_BUZZER ( FLAG_BIT_BUZZER | COMMAND_BUZZER_LOW_VOLUME |COMMAND_BUZZER_MEDIUM_VOLUME | COMMAND_BUZZER_HIGH_VOLUME)
#define FLAG_MASK_LIGHT ( COMMAND_LIGHT_ON | COMMAND_LIGHT_OFF | COMMAND_LIGHT_CHANGE )
